name = inv_manager
title = Inventory Manager
description = View and manage players inventories in real time, with snapshots and an audit log.
author = Flay Krunegan
min_minetest_version = 5.17
optional_depends = unified_inventory, sfinv, i3, 3d_armor, mcl_armor, mcl_chests, mcl_offhand, mcl_inventory